/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booktap;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sravy
 */
public class AddPost extends javax.swing.JFrame {

    /**
     * Creates new form AddPost
     */
    
    String image_path = null; 
    String username;
    public AddPost(String u) {
        this.username = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AddPost = new javax.swing.JPanel();
        jPanel_Inner = new javax.swing.JPanel();
        jLabel_Author = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Review = new javax.swing.JLabel();
        jLabel_Genre = new javax.swing.JLabel();
        jLabel_Rating = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();
        jButton_Upload = new javax.swing.JButton();
        jLabel_ImagePath = new javax.swing.JLabel();
        jButton_Submit = new javax.swing.JButton();
        jTextField_Author = new javax.swing.JTextField();
        jTextField_Rating = new javax.swing.JTextField();
        jTextField_Genre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Summary = new javax.swing.JTextArea();
        jTextField_BookName = new javax.swing.JTextField();
        jButton_GoBack = new javax.swing.JButton();
        jLabel_UploadedImage = new javax.swing.JLabel();
        jLabel_Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NEW POST");
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));

        jPanel_AddPost.setBackground(new java.awt.Color(43, 37, 56));
        jPanel_AddPost.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel_Inner.setBackground(new java.awt.Color(17, 94, 111));

        jLabel_Author.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel_Author.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Author.setText("Book author ");

        jLabel_Name.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Name.setText("Book name ");

        jLabel_Review.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel_Review.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Review.setText("Book review ");

        jLabel_Genre.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel_Genre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Genre.setText("Genre ");

        jLabel_Rating.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel_Rating.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rating.setText("Rating ");

        jLabel_Image.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel_Image.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image.setText("Image");

        jButton_Upload.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Upload.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Upload.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Upload.setText("Upload");
        jButton_Upload.setBorder(null);
        jButton_Upload.setFocusPainted(false);
        jButton_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UploadActionPerformed(evt);
            }
        });

        jLabel_ImagePath.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel_ImagePath.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ImagePath.setText("image path");

        jButton_Submit.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Submit.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Submit.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Submit.setText("Submit");
        jButton_Submit.setBorder(null);
        jButton_Submit.setFocusPainted(false);
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });

        jTextField_Author.setBackground(new java.awt.Color(43, 37, 56));
        jTextField_Author.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jTextField_Author.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Author.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AuthorActionPerformed(evt);
            }
        });

        jTextField_Rating.setBackground(new java.awt.Color(43, 37, 56));
        jTextField_Rating.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jTextField_Rating.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Rating.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_Rating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RatingActionPerformed(evt);
            }
        });

        jTextField_Genre.setBackground(new java.awt.Color(43, 37, 56));
        jTextField_Genre.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jTextField_Genre.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Genre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_Genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GenreActionPerformed(evt);
            }
        });

        jTextArea_Summary.setBackground(new java.awt.Color(43, 37, 56));
        jTextArea_Summary.setColumns(20);
        jTextArea_Summary.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jTextArea_Summary.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Summary.setLineWrap(true);
        jTextArea_Summary.setRows(5);
        jTextArea_Summary.setWrapStyleWord(true);
        jTextArea_Summary.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea_Summary);

        jTextField_BookName.setBackground(new java.awt.Color(43, 37, 56));
        jTextField_BookName.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jTextField_BookName.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_BookName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextField_BookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BookNameActionPerformed(evt);
            }
        });

        jButton_GoBack.setBackground(new java.awt.Color(255, 182, 28));
        jButton_GoBack.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_GoBack.setForeground(new java.awt.Color(43, 37, 56));
        jButton_GoBack.setText("Go Back");
        jButton_GoBack.setBorder(null);
        jButton_GoBack.setFocusPainted(false);
        jButton_GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GoBackActionPerformed(evt);
            }
        });

        jLabel_UploadedImage.setPreferredSize(new java.awt.Dimension(300, 450));

        jLabel_Title.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setText("New Post");

        javax.swing.GroupLayout jPanel_InnerLayout = new javax.swing.GroupLayout(jPanel_Inner);
        jPanel_Inner.setLayout(jPanel_InnerLayout);
        jPanel_InnerLayout.setHorizontalGroup(
            jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InnerLayout.createSequentialGroup()
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InnerLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_InnerLayout.createSequentialGroup()
                                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Review)
                                    .addComponent(jLabel_Rating)
                                    .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_BookName, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Rating, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_ImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_Name)
                            .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Author)
                            .addComponent(jLabel_Genre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(jPanel_InnerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton_GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addComponent(jLabel_UploadedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel_InnerLayout.setVerticalGroup(
            jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InnerLayout.createSequentialGroup()
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InnerLayout.createSequentialGroup()
                        .addComponent(jLabel_Name)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Author)
                            .addComponent(jTextField_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField_BookName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Genre)
                    .addComponent(jTextField_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InnerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_InnerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_Review)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Rating, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Rating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Upload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ImagePath)
                .addGap(26, 26, 26)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InnerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_UploadedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_AddPostLayout = new javax.swing.GroupLayout(jPanel_AddPost);
        jPanel_AddPost.setLayout(jPanel_AddPostLayout);
        jPanel_AddPostLayout.setHorizontalGroup(
            jPanel_AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AddPostLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel_Inner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel_AddPostLayout.setVerticalGroup(
            jPanel_AddPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AddPostLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel_Inner, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_AddPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AddPost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_BookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BookNameActionPerformed

    private void jTextField_RatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RatingActionPerformed

    private void jTextField_AuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AuthorActionPerformed

    private void jTextField_GenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenreActionPerformed

    private void jButton_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UploadActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            FileNameExtensionFilter extension = new FileNameExtensionFilter("*Images",".png",".jpg",".jpeg");
            chooser.addChoosableFileFilter(extension);

            int filestate = chooser.showSaveDialog(null);
            if(filestate == JFileChooser.APPROVE_OPTION)
            {
                File selectedImage = chooser.getSelectedFile();
                image_path = selectedImage.getAbsolutePath();
                if(image_path.endsWith(".jpeg") || image_path.endsWith(".jpg") || image_path.endsWith(".png")){
                    jLabel_ImagePath.setText(image_path);
                    Image getAbsolutePath = null;
                    ImageIcon icon = new ImageIcon(image_path);
                    Image image = icon.getImage().getScaledInstance(jLabel_UploadedImage.getWidth(), jLabel_UploadedImage.getHeight(), Image.SCALE_SMOOTH);
                    jLabel_UploadedImage.setIcon(icon);
                    JOptionPane.showMessageDialog(this, "Image uploaded successfully!");
                }
                else{
                        JOptionPane.showMessageDialog(this, "Invalid file format.");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton_UploadActionPerformed

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
        // TODO add your handling code here:
        String bookName = jTextField_BookName.getText();
        String bookAuthor = jTextField_Author.getText();
        String bookGenre = jTextField_Genre.getText();
        String bookRating = jTextField_Rating.getText();
        String bookSummary = jTextArea_Summary.getText();
        if(bookName.trim().equals("") || bookAuthor.trim().equals("") || bookGenre.trim().equals("") || bookRating.trim().equals(""))
        {   
            JOptionPane.showMessageDialog(this, "Please enter all details.");
        }
        else{
            try{
                Float rating = Float.parseFloat(bookRating); 
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","it175","sravya");
                PreparedStatement pstmt = con.prepareStatement("INSERT INTO POSTS(Name, Author, Genre, Review, Rating, Image, Username, Time) VALUES(?,?,?,?,?,?,?,?)");
                pstmt.setString(1, bookName);
                pstmt.setString(2, bookAuthor);
                pstmt.setString(3, bookGenre);
                pstmt.setString(4, bookSummary);
                pstmt.setFloat(5, rating);
                FileInputStream in = new FileInputStream(image_path);
                pstmt.setBinaryStream(6,in,in.available());
                pstmt.setString(7, username);
                Timestamp t = new Timestamp(System.currentTimeMillis());
                pstmt.setTimestamp(8, t);
                pstmt.execute();
                JOptionPane.showMessageDialog(this,"Success!");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jButton_GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GoBackActionPerformed
        // TODO add your handling code here:
        Posts p = new Posts(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_GoBackActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddPost().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GoBack;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JButton jButton_Upload;
    private javax.swing.JLabel jLabel_Author;
    private javax.swing.JLabel jLabel_Genre;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_ImagePath;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Rating;
    private javax.swing.JLabel jLabel_Review;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_UploadedImage;
    private javax.swing.JPanel jPanel_AddPost;
    private javax.swing.JPanel jPanel_Inner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Summary;
    private javax.swing.JTextField jTextField_Author;
    private javax.swing.JTextField jTextField_BookName;
    private javax.swing.JTextField jTextField_Genre;
    private javax.swing.JTextField jTextField_Rating;
    // End of variables declaration//GEN-END:variables
}
