/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booktap;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author srile
 */
public class BooksPage extends javax.swing.JFrame {

    /**
     * Creates new form BooksPage
     */
    String username;
    public BooksPage(String u) {
        this.username = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OuterPanel = new javax.swing.JPanel();
        jScrollPane_Main = new javax.swing.JScrollPane();
        jPanel_Inner = new javax.swing.JPanel();
        genresList = new javax.swing.JComboBox<>();
        filter = new javax.swing.JButton();
        BooksHolder = new javax.swing.JScrollPane();
        BooksHolderPanel = new javax.swing.JPanel();
        BookInfoHolder = new javax.swing.JPanel();
        bookNameLabel = new javax.swing.JLabel();
        authorNameLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        bookSummaryLabel = new javax.swing.JLabel();
        bookNameTF = new javax.swing.JTextField();
        authorNameTF = new javax.swing.JTextField();
        genreTF = new javax.swing.JTextField();
        publisherTF = new javax.swing.JTextField();
        bookSummaryHolder = new javax.swing.JScrollPane();
        bookSummaryTA = new javax.swing.JTextArea();
        jLabel_Image = new javax.swing.JLabel();
        TopNav = new javax.swing.JPanel();
        jButton_Books = new javax.swing.JButton();
        jButton_Posts = new javax.swing.JButton();
        jButton_Trending = new javax.swing.JButton();
        jButton_Profile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOKS ");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        OuterPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel_Inner.setBackground(new java.awt.Color(43, 37, 56));
        jPanel_Inner.setPreferredSize(new java.awt.Dimension(1000, 1261));

        genresList.setBackground(new java.awt.Color(17, 94, 111));
        genresList.setEditable(true);
        genresList.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        genresList.setForeground(new java.awt.Color(255, 255, 255));
        genresList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Genre...", "Adventure", "Children", "Classics", "Fantasy", "Fiction", "Horror", "Mystery", "Non-Fiction", "Poetry", "Romance" }));
        genresList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        filter.setBackground(new java.awt.Color(17, 94, 111));
        filter.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        filter.setForeground(new java.awt.Color(255, 255, 255));
        filter.setText("Apply Filter");
        filter.setBorderPainted(false);
        filter.setFocusPainted(false);
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        displayAllBooks();
        BooksHolderPanel.setBackground(new java.awt.Color(43,37,56));
        BooksHolderPanel.setLayout(new java.awt.GridLayout(0, 2));
        BooksHolder.setViewportView(BooksHolderPanel);

        BookInfoHolder.setBackground(new java.awt.Color(17, 94, 111));
        BookInfoHolder.setToolTipText("");

        bookNameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        bookNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookNameLabel.setText("Book Name:");

        authorNameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        authorNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        authorNameLabel.setText("Author Name:");

        genreLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        genreLabel.setForeground(new java.awt.Color(255, 255, 255));
        genreLabel.setText("Genre:");

        publisherLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        publisherLabel.setForeground(new java.awt.Color(255, 255, 255));
        publisherLabel.setText("Publisher:");

        bookSummaryLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        bookSummaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookSummaryLabel.setText("Book Summary:");

        bookNameTF.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        bookNameTF.setForeground(new java.awt.Color(0, 51, 102));
        bookNameTF.setToolTipText("");
        bookNameTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        bookNameTF.setMargin(new java.awt.Insets(5, 5, 5, 5));
        bookNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameTFActionPerformed(evt);
            }
        });

        authorNameTF.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        authorNameTF.setForeground(new java.awt.Color(0, 51, 102));
        authorNameTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        authorNameTF.setMargin(new java.awt.Insets(5, 5, 5, 5));
        authorNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorNameTFActionPerformed(evt);
            }
        });

        genreTF.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        genreTF.setForeground(new java.awt.Color(0, 51, 102));
        genreTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        genreTF.setMargin(new java.awt.Insets(5, 5, 5, 5));
        genreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreTFActionPerformed(evt);
            }
        });

        publisherTF.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        publisherTF.setForeground(new java.awt.Color(0, 51, 102));
        publisherTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        publisherTF.setMargin(new java.awt.Insets(5, 5, 5, 5));
        publisherTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherTFActionPerformed(evt);
            }
        });

        bookSummaryTA.setColumns(20);
        bookSummaryTA.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        bookSummaryTA.setForeground(new java.awt.Color(0, 51, 102));
        bookSummaryTA.setLineWrap(true);
        bookSummaryTA.setRows(5);
        bookSummaryTA.setWrapStyleWord(true);
        bookSummaryTA.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        bookSummaryTA.setMargin(new java.awt.Insets(5, 5, 5, 5));
        bookSummaryHolder.setViewportView(bookSummaryTA);

        jLabel_Image.setPreferredSize(new java.awt.Dimension(200, 300));

        javax.swing.GroupLayout BookInfoHolderLayout = new javax.swing.GroupLayout(BookInfoHolder);
        BookInfoHolder.setLayout(BookInfoHolderLayout);
        BookInfoHolderLayout.setHorizontalGroup(
            BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookInfoHolderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookInfoHolderLayout.createSequentialGroup()
                        .addComponent(bookSummaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bookSummaryHolder)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookInfoHolderLayout.createSequentialGroup()
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(genreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorNameTF)
                            .addComponent(genreTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookInfoHolderLayout.createSequentialGroup()
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bookNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(publisherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisherTF)
                            .addComponent(bookNameTF))))
                .addGap(71, 71, 71)
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        BookInfoHolderLayout.setVerticalGroup(
            BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookInfoHolderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameTF))
                .addGap(18, 18, 18)
                .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookInfoHolderLayout.createSequentialGroup()
                        .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BookInfoHolderLayout.createSequentialGroup()
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorNameTF))
                        .addGap(18, 18, 18)
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreTF))
                        .addGap(18, 18, 18)
                        .addGroup(BookInfoHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherTF))
                        .addGap(28, 28, 28)
                        .addComponent(bookSummaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookSummaryHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))))
        );

        javax.swing.GroupLayout jPanel_InnerLayout = new javax.swing.GroupLayout(jPanel_Inner);
        jPanel_Inner.setLayout(jPanel_InnerLayout);
        jPanel_InnerLayout.setHorizontalGroup(
            jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InnerLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BookInfoHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BooksHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                    .addGroup(jPanel_InnerLayout.createSequentialGroup()
                        .addComponent(genresList, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel_InnerLayout.setVerticalGroup(
            jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InnerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel_InnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genresList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(BooksHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(BookInfoHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jScrollPane_Main.setViewportView(jPanel_Inner);

        TopNav.setBackground(new java.awt.Color(43, 37, 56));

        jButton_Books.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Books.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Books.setText("Books");
        jButton_Books.setBorder(null);
        jButton_Books.setBorderPainted(false);
        jButton_Books.setFocusPainted(false);
        jButton_Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BooksActionPerformed(evt);
            }
        });

        jButton_Posts.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Posts.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Posts.setText("Posts");
        jButton_Posts.setBorder(null);
        jButton_Posts.setBorderPainted(false);
        jButton_Posts.setFocusPainted(false);
        jButton_Posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PostsActionPerformed(evt);
            }
        });

        jButton_Trending.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Trending.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Trending.setText("Trending");
        jButton_Trending.setBorder(null);
        jButton_Trending.setBorderPainted(false);
        jButton_Trending.setFocusPainted(false);
        jButton_Trending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TrendingActionPerformed(evt);
            }
        });

        jButton_Profile.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Profile.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Profile.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Profile.setText("Profile");
        jButton_Profile.setBorder(null);
        jButton_Profile.setFocusPainted(false);
        jButton_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfileActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 182, 28));
        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(43, 37, 56));
        jButton1.setText("Settings");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_Home.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Home.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Home.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Home.setText("Home");
        jButton_Home.setBorder(null);
        jButton_Home.setFocusPainted(false);
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopNavLayout = new javax.swing.GroupLayout(TopNav);
        TopNav.setLayout(TopNavLayout);
        TopNavLayout.setHorizontalGroup(
            TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopNavLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Trending, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        TopNavLayout.setVerticalGroup(
            TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopNavLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Trending, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout OuterPanelLayout = new javax.swing.GroupLayout(OuterPanel);
        OuterPanel.setLayout(OuterPanelLayout);
        OuterPanelLayout.setHorizontalGroup(
            OuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(TopNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OuterPanelLayout.setVerticalGroup(
            OuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OuterPanelLayout.createSequentialGroup()
                .addComponent(TopNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OuterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OuterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1451, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PostsActionPerformed
        // TODO add your handling code here:
        Posts p = new Posts(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_PostsActionPerformed

//    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt){
//        HomePage h = new HomePage();
//        h.show();
//        dispose();
//    }
    private void jButton_TrendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TrendingActionPerformed
        // TODO add your handling code here:
        Trending t = new Trending(this.username);
        t.show();
        dispose();
    }//GEN-LAST:event_jButton_TrendingActionPerformed

    private void jButton_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfileActionPerformed
        // TODO add your handling code here:
        Profile p = new Profile(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_ProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Settings s = new Settings(this.username);
        s.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BooksActionPerformed

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
        HomePage h = new HomePage(this.username);
        h.show();
        dispose();
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void bookNameTFActionPerformed(java.awt.event.ActionEvent evt) {
        // to do alot
    }

    private void authorNameTFActionPerformed(java.awt.event.ActionEvent evt) {
        // to do alot
    }

    private void genreTFActionPerformed(java.awt.event.ActionEvent evt) {
        // to do alot
    }

    private void publisherTFActionPerformed(java.awt.event.ActionEvent evt) {
        // to do alot
    }

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {
        // GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BooksHolderPanel.removeAll();
        revalidate();
        repaint();
        int index = genresList.getSelectedIndex();
        String genres[] = { "None Selected", "Adventure", "Children", "Classics", "Fantasy", "Fiction", "Horror",
                "Mystery", "Non-Fiction", "Poetry", "Romance" };
        javax.swing.JButton[] buttons = new javax.swing.JButton[100];
        int i = 0;

        if (index != 0) {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");

                Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "it175",
                        "sravya");

                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(
                        "SELECT * FROM Books INNER JOIN GENRES ON Books.BOOKID=GENRES.BOOKID WHERE GENRES.GENRENAME='"
                                + genres[index] + "'");

                String books[] = new String[100];

                while (rs.next()) {
                    books[i] = rs.getString(2);
                    i++;
                }
                if (i == 0) {
                    BooksHolderPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
                    javax.swing.JLabel message = new javax.swing.JLabel("NO BOOKS IN THIS GENRE!");
                    message.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
                    message.setAlignmentY(java.awt.Component.CENTER_ALIGNMENT);
                    BooksHolderPanel.add(message);
                    pack();
                    setVisible(true);
                } else {
                    BooksHolderPanel.setLayout(new java.awt.GridLayout(0, 2));
                    for (int j = 0; j < i; j++) {
                        javax.swing.JButton temp = new javax.swing.JButton(books[j]);
                        temp.setBackground(new Color(17, 94, 111));
                        temp.setForeground(java.awt.Color.WHITE);
                        temp.setFocusPainted(false);
                        temp.setFont(new java.awt.Font("Malgun Gothic", 1, 14));
                        temp.setVisible(true);
                        temp.addActionListener(new java.awt.event.ActionListener() {
                            @Override
                            public void actionPerformed(java.awt.event.ActionEvent e) {
                                displaySelectedBook(e, genres[index]);

                            }
                        });
                        buttons[j] = temp;

                        BooksHolderPanel.add(buttons[j]);
                    }
                    pack();
                    setVisible(true);
                }
                con.close();
            } catch (Exception exc) {
                System.out.println(exc);
            }

        } else {
            displayAllBooks();
            pack();
            setVisible(true);
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        HomePage h = new HomePage(this.username);
        h.show();
        dispose();
    }// GEN-LAST:event_HomeActionPerformed

    private void displaySelectedBook(java.awt.event.ActionEvent evt, String genre) {
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "it175",
                    "sravya");

            String temp = evt.getActionCommand();
            String bname = temp.replaceAll("'", "''");

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM BOOKS WHERE BOOKNAME='" + bname + "'");

            int bid = 1;
            String aname = "", pname = "", bsummary = "";
            while (rs.next()) {
                bid = rs.getInt(1);
                aname = rs.getString(3);
                pname = rs.getString(6);
                bsummary = rs.getString(4);
                Blob b = rs.getBlob(7);
		byte barr[] = b.getBytes(1,(int)b.length());
                ImageIcon icon = new ImageIcon(barr);
                java.awt.Image img = icon.getImage();
                java.awt.Image scale = img.getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(),java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaled = new ImageIcon(scale);
                jLabel_Image.setIcon(scaled);
            }

            genre = getGenre(bid);

            bookNameTF.setText(bname);
            authorNameTF.setText(aname);
            genreTF.setText(genre);
            publisherTF.setText(pname);
            bookSummaryTA.setText(bsummary);       
            

            con.close();

        } catch (Exception e) {
            System.out.println(e.getStackTrace());
        }
    }

    public void displayAllBooks() {
        BooksHolderPanel.setLayout(new java.awt.GridLayout(0, 2));
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "it175",
                    "sravya");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM Books");

            while (rs.next()) {
                String bname = rs.getString(2);
                String genre = rs.getString(6);
                
                if ("".equals(bname) || "".equals(genre)) {
                    break;
                }

                javax.swing.JButton b = new javax.swing.JButton(bname);
                b.setFont(new java.awt.Font("Malgun Gothic", Font.PLAIN, 13));
                b.setForeground(java.awt.Color.WHITE);
                b.setBackground(new Color(17, 94, 111));
                b.setFocusPainted(false);
                b.setBorder(BorderFactory.createLineBorder(Color.black));
                b.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        displaySelectedBook(e, genre);
                    }
                });
                BooksHolderPanel.add(b);
            }

            // pack();
            // setVisible(true);
            con.close();
        } catch (Exception exc) {
            System.out.println(exc);
        }
    }

    public String getGenre(int bookID) {
        String genre = "";
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");

            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "it175",
                    "sravya");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM Genres WHERE BOOKID=" + bookID);

            while (rs.next()) {
                genre += rs.getString(2) + " ";
            }
            
        } catch (Exception e) {
            System.out.println(e.getStackTrace());
        }

        return genre;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//        // (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//         * look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BooksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BooksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BooksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BooksPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        // </editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BooksPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookInfoHolder;
    private javax.swing.JScrollPane BooksHolder;
    private javax.swing.JPanel BooksHolderPanel;
    private javax.swing.JPanel OuterPanel;
    private javax.swing.JPanel TopNav;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JTextField authorNameTF;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTF;
    private javax.swing.JScrollPane bookSummaryHolder;
    private javax.swing.JLabel bookSummaryLabel;
    private javax.swing.JTextArea bookSummaryTA;
    private javax.swing.JButton filter;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JTextField genreTF;
    private javax.swing.JComboBox<String> genresList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Books;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Posts;
    private javax.swing.JButton jButton_Profile;
    private javax.swing.JButton jButton_Trending;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JPanel jPanel_Inner;
    private javax.swing.JScrollPane jScrollPane_Main;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JTextField publisherTF;
    // End of variables declaration//GEN-END:variables
}
