package booktap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srile
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    String username;
    public HomePage(String u) {
        this.username = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jPanel_Sub = new javax.swing.JPanel();
        jScrollPane_Main = new javax.swing.JScrollPane();
        jPanel_Information = new javax.swing.JPanel();
        jScrollPane_TA = new javax.swing.JScrollPane();
        jTextArea_Introduction = new javax.swing.JTextArea();
        jLabel_Image = new javax.swing.JLabel();
        jLabel_Genres = new javax.swing.JLabel();
        jPanel_Genres = new javax.swing.JPanel();
        jPanel_Adventure = new javax.swing.JPanel();
        advLabel = new javax.swing.JLabel();
        advImage = new javax.swing.JLabel();
        jPanel_Children = new javax.swing.JPanel();
        childrenLabel = new javax.swing.JLabel();
        childrenImage = new javax.swing.JLabel();
        jPanel_Classics = new javax.swing.JPanel();
        classicsLabel = new javax.swing.JLabel();
        classicsImage = new javax.swing.JLabel();
        jPanel_NonFiction = new javax.swing.JPanel();
        nfLabel = new javax.swing.JLabel();
        nfImage = new javax.swing.JLabel();
        jPanel_Fantasy = new javax.swing.JPanel();
        fantasyLabel = new javax.swing.JLabel();
        fantasyImage = new javax.swing.JLabel();
        jPanel_Fiction = new javax.swing.JPanel();
        fictionLabel = new javax.swing.JLabel();
        fictionImage = new javax.swing.JLabel();
        jPanel_Horror = new javax.swing.JPanel();
        horrorLabel = new javax.swing.JLabel();
        horrorImage = new javax.swing.JLabel();
        jPanel_Romance = new javax.swing.JPanel();
        romLabel = new javax.swing.JLabel();
        romImage = new javax.swing.JLabel();
        jPanel_Mystery = new javax.swing.JPanel();
        mysLabel = new javax.swing.JLabel();
        mysImage = new javax.swing.JLabel();
        jPanel_Poetry = new javax.swing.JPanel();
        poetryLabel = new javax.swing.JLabel();
        poetryImage = new javax.swing.JLabel();
        TopNav = new javax.swing.JPanel();
        jButton_Home = new javax.swing.JButton();
        jButton_Books = new javax.swing.JButton();
        jButton_Posts = new javax.swing.JButton();
        jButton_Trending = new javax.swing.JButton();
        jLabel_Welcome = new javax.swing.JLabel();
        jButton_Settings = new javax.swing.JButton();
        jButton_Profile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setSize(new java.awt.Dimension(1000, 600));

        jPanel_Main.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane_Main.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel_Information.setBackground(new java.awt.Color(43, 37, 56));

        jTextArea_Introduction.setEditable(false);
        jTextArea_Introduction.setBackground(new java.awt.Color(43, 37, 56));
        jTextArea_Introduction.setColumns(20);
        jTextArea_Introduction.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jTextArea_Introduction.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_Introduction.setLineWrap(true);
        jTextArea_Introduction.setRows(5);
        jTextArea_Introduction.setText("BookTap is a community for book lovers to come together and share their ideas and thoughts. It is THE application for bibliophiles. You have thousands of books at touch of your finger and can see what the rest of the community is thinking about a book. Some awesome features you can explore are: Posting: You can post about your favorite books and check out other posts as well!  Books: If you want to view information regarding a book, head on over to the Books tab! Trending: Just like songs, we have compiled the top trending books in every genre.");
        jTextArea_Introduction.setWrapStyleWord(true);
        jTextArea_Introduction.setBorder(null);
        jScrollPane_TA.setViewportView(jTextArea_Introduction);

        jLabel_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/HomePageMainImage.PNG"))); // NOI18N

        jLabel_Genres.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel_Genres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Genres.setText("Available Genres...");

        jPanel_Genres.setBackground(new java.awt.Color(17, 94, 111));

        jPanel_Adventure.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Adventure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        advLabel.setBackground(new java.awt.Color(255, 255, 255));
        advLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        advLabel.setForeground(new java.awt.Color(43, 37, 56));
        advLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        advLabel.setText("Adventure");
        advLabel.setOpaque(true);

        advImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Adventure.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_AdventureLayout = new javax.swing.GroupLayout(jPanel_Adventure);
        jPanel_Adventure.setLayout(jPanel_AdventureLayout);
        jPanel_AdventureLayout.setHorizontalGroup(
            jPanel_AdventureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(advLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(advImage)
        );
        jPanel_AdventureLayout.setVerticalGroup(
            jPanel_AdventureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_AdventureLayout.createSequentialGroup()
                .addComponent(advImage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Children.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Children.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        childrenLabel.setBackground(new java.awt.Color(255, 255, 255));
        childrenLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        childrenLabel.setForeground(new java.awt.Color(43, 37, 56));
        childrenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        childrenLabel.setText("Children");

        childrenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Children.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_ChildrenLayout = new javax.swing.GroupLayout(jPanel_Children);
        jPanel_Children.setLayout(jPanel_ChildrenLayout);
        jPanel_ChildrenLayout.setHorizontalGroup(
            jPanel_ChildrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childrenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(childrenImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ChildrenLayout.setVerticalGroup(
            jPanel_ChildrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChildrenLayout.createSequentialGroup()
                .addComponent(childrenImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(childrenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Classics.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Classics.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        classicsLabel.setBackground(new java.awt.Color(255, 255, 255));
        classicsLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        classicsLabel.setForeground(new java.awt.Color(43, 37, 56));
        classicsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classicsLabel.setText("Classics");

        classicsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Classics.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_ClassicsLayout = new javax.swing.GroupLayout(jPanel_Classics);
        jPanel_Classics.setLayout(jPanel_ClassicsLayout);
        jPanel_ClassicsLayout.setHorizontalGroup(
            jPanel_ClassicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classicsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(classicsImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ClassicsLayout.setVerticalGroup(
            jPanel_ClassicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ClassicsLayout.createSequentialGroup()
                .addComponent(classicsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classicsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_NonFiction.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_NonFiction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nfLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        nfLabel.setForeground(new java.awt.Color(43, 37, 56));
        nfLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nfLabel.setText("Non-Fiction");

        nfImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Non-Fiction.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_NonFictionLayout = new javax.swing.GroupLayout(jPanel_NonFiction);
        jPanel_NonFiction.setLayout(jPanel_NonFictionLayout);
        jPanel_NonFictionLayout.setHorizontalGroup(
            jPanel_NonFictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nfImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_NonFictionLayout.setVerticalGroup(
            jPanel_NonFictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NonFictionLayout.createSequentialGroup()
                .addComponent(nfImage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Fantasy.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Fantasy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fantasyLabel.setBackground(new java.awt.Color(255, 255, 255));
        fantasyLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        fantasyLabel.setForeground(new java.awt.Color(43, 37, 56));
        fantasyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fantasyLabel.setText("Fantasy");

        fantasyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Fantasy.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_FantasyLayout = new javax.swing.GroupLayout(jPanel_Fantasy);
        jPanel_Fantasy.setLayout(jPanel_FantasyLayout);
        jPanel_FantasyLayout.setHorizontalGroup(
            jPanel_FantasyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fantasyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fantasyImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_FantasyLayout.setVerticalGroup(
            jPanel_FantasyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FantasyLayout.createSequentialGroup()
                .addComponent(fantasyImage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fantasyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Fiction.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Fiction.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fictionLabel.setBackground(new java.awt.Color(255, 255, 255));
        fictionLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        fictionLabel.setForeground(new java.awt.Color(43, 37, 56));
        fictionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fictionLabel.setText("Fiction");

        fictionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Fiction.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_FictionLayout = new javax.swing.GroupLayout(jPanel_Fiction);
        jPanel_Fiction.setLayout(jPanel_FictionLayout);
        jPanel_FictionLayout.setHorizontalGroup(
            jPanel_FictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fictionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fictionImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_FictionLayout.setVerticalGroup(
            jPanel_FictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FictionLayout.createSequentialGroup()
                .addComponent(fictionImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fictionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Horror.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Horror.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        horrorLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        horrorLabel.setForeground(new java.awt.Color(43, 37, 56));
        horrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horrorLabel.setText("Horror");

        horrorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Horror.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_HorrorLayout = new javax.swing.GroupLayout(jPanel_Horror);
        jPanel_Horror.setLayout(jPanel_HorrorLayout);
        jPanel_HorrorLayout.setHorizontalGroup(
            jPanel_HorrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(horrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(horrorImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_HorrorLayout.setVerticalGroup(
            jPanel_HorrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_HorrorLayout.createSequentialGroup()
                .addComponent(horrorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Romance.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Romance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        romLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        romLabel.setForeground(new java.awt.Color(43, 37, 56));
        romLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        romLabel.setText("Romance");

        romImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Romance.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_RomanceLayout = new javax.swing.GroupLayout(jPanel_Romance);
        jPanel_Romance.setLayout(jPanel_RomanceLayout);
        jPanel_RomanceLayout.setHorizontalGroup(
            jPanel_RomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(romLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(romImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_RomanceLayout.setVerticalGroup(
            jPanel_RomanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RomanceLayout.createSequentialGroup()
                .addComponent(romImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(romLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Mystery.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Mystery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mysLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        mysLabel.setForeground(new java.awt.Color(43, 37, 56));
        mysLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mysLabel.setText("Mystery");

        mysImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Mystery.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_MysteryLayout = new javax.swing.GroupLayout(jPanel_Mystery);
        jPanel_Mystery.setLayout(jPanel_MysteryLayout);
        jPanel_MysteryLayout.setHorizontalGroup(
            jPanel_MysteryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mysImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_MysteryLayout.setVerticalGroup(
            jPanel_MysteryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MysteryLayout.createSequentialGroup()
                .addComponent(mysImage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Poetry.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Poetry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poetryLabel.setBackground(new java.awt.Color(255, 255, 255));
        poetryLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        poetryLabel.setForeground(new java.awt.Color(43, 37, 56));
        poetryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poetryLabel.setText("Poetry");

        poetryImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage_images/Poetry.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel_PoetryLayout = new javax.swing.GroupLayout(jPanel_Poetry);
        jPanel_Poetry.setLayout(jPanel_PoetryLayout);
        jPanel_PoetryLayout.setHorizontalGroup(
            jPanel_PoetryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(poetryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(poetryImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_PoetryLayout.setVerticalGroup(
            jPanel_PoetryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PoetryLayout.createSequentialGroup()
                .addComponent(poetryImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poetryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel_GenresLayout = new javax.swing.GroupLayout(jPanel_Genres);
        jPanel_Genres.setLayout(jPanel_GenresLayout);
        jPanel_GenresLayout.setHorizontalGroup(
            jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GenresLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Adventure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Fiction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Children, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Horror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Poetry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Mystery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Classics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Romance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Fantasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_NonFiction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel_GenresLayout.setVerticalGroup(
            jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GenresLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Classics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Children, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Adventure, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Fantasy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_NonFiction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Fiction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Horror, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Mystery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel_GenresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Poetry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Romance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_InformationLayout = new javax.swing.GroupLayout(jPanel_Information);
        jPanel_Information.setLayout(jPanel_InformationLayout);
        jPanel_InformationLayout.setHorizontalGroup(
            jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Genres, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addComponent(jScrollPane_TA, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Genres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel_InformationLayout.setVerticalGroup(
            jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane_TA, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jLabel_Genres, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Genres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jScrollPane_TA.setBorder(null);

        jScrollPane_Main.setViewportView(jPanel_Information);

        javax.swing.GroupLayout jPanel_SubLayout = new javax.swing.GroupLayout(jPanel_Sub);
        jPanel_Sub.setLayout(jPanel_SubLayout);
        jPanel_SubLayout.setHorizontalGroup(
            jPanel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_SubLayout.setVerticalGroup(
            jPanel_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        TopNav.setBackground(new java.awt.Color(43, 37, 56));

        jButton_Home.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Home.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Home.setText("Home");
        jButton_Home.setBorder(null);
        jButton_Home.setBorderPainted(false);
        jButton_Home.setFocusPainted(false);
        jButton_Home.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        jButton_Books.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Books.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Books.setText("Books");
        jButton_Books.setBorder(null);
        jButton_Books.setBorderPainted(false);
        jButton_Books.setFocusPainted(false);
        jButton_Books.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton_Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BooksActionPerformed(evt);
            }
        });

        jButton_Posts.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Posts.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Posts.setText("Posts");
        jButton_Posts.setBorder(null);
        jButton_Posts.setBorderPainted(false);
        jButton_Posts.setFocusPainted(false);
        jButton_Posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PostsActionPerformed(evt);
            }
        });

        jButton_Trending.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Trending.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Trending.setText("Trending");
        jButton_Trending.setBorder(null);
        jButton_Trending.setBorderPainted(false);
        jButton_Trending.setFocusPainted(false);
        jButton_Trending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TrendingActionPerformed(evt);
            }
        });

        jLabel_Welcome.setBackground(new java.awt.Color(17, 94, 111));
        jLabel_Welcome.setFont(new java.awt.Font("Malgun Gothic", 1, 28)); // NOI18N
        jLabel_Welcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Welcome.setText("Welcome to BookTap!");
        jLabel_Welcome.setOpaque(true);

        jButton_Settings.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Settings.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Settings.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Settings.setText("Settings");
        jButton_Settings.setBorder(null);
        jButton_Settings.setFocusPainted(false);
        jButton_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SettingsActionPerformed(evt);
            }
        });

        jButton_Profile.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Profile.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton_Profile.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Profile.setText("Profile");
        jButton_Profile.setBorder(null);
        jButton_Profile.setFocusPainted(false);
        jButton_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopNavLayout = new javax.swing.GroupLayout(TopNav);
        TopNav.setLayout(TopNavLayout);
        TopNavLayout.setHorizontalGroup(
            TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopNavLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Trending, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jLabel_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopNavLayout.setVerticalGroup(
            TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopNavLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TopNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Trending, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(jLabel_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addComponent(TopNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BooksActionPerformed
        // TODO add your handling code here:
        BooksPage b = new BooksPage(this.username);
        b.show();
        dispose();
    }//GEN-LAST:event_jButton_BooksActionPerformed

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void jButton_PostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PostsActionPerformed
        // TODO add your handling code here:
        Posts p = new Posts(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_PostsActionPerformed

    private void jButton_TrendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TrendingActionPerformed
        // TODO add your handling code here:
        Trending t = new Trending(this.username);
        t.show();
        dispose();
    }//GEN-LAST:event_jButton_TrendingActionPerformed

    private void jButton_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfileActionPerformed
        // TODO add your handling code here:
        Profile p = new Profile(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_ProfileActionPerformed

    private void jButton_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SettingsActionPerformed
        // TODO add your handling code here:
        Settings s = new Settings(this.username);
        s.show();
        dispose();
    }//GEN-LAST:event_jButton_SettingsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomePage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TopNav;
    private javax.swing.JLabel advImage;
    private javax.swing.JLabel advLabel;
    private javax.swing.JLabel childrenImage;
    private javax.swing.JLabel childrenLabel;
    private javax.swing.JLabel classicsImage;
    private javax.swing.JLabel classicsLabel;
    private javax.swing.JLabel fantasyImage;
    private javax.swing.JLabel fantasyLabel;
    private javax.swing.JLabel fictionImage;
    private javax.swing.JLabel fictionLabel;
    private javax.swing.JLabel horrorImage;
    private javax.swing.JLabel horrorLabel;
    private javax.swing.JButton jButton_Books;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Posts;
    private javax.swing.JButton jButton_Profile;
    private javax.swing.JButton jButton_Settings;
    private javax.swing.JButton jButton_Trending;
    private javax.swing.JLabel jLabel_Genres;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Welcome;
    private javax.swing.JPanel jPanel_Adventure;
    private javax.swing.JPanel jPanel_Children;
    private javax.swing.JPanel jPanel_Classics;
    private javax.swing.JPanel jPanel_Fantasy;
    private javax.swing.JPanel jPanel_Fiction;
    private javax.swing.JPanel jPanel_Genres;
    private javax.swing.JPanel jPanel_Horror;
    private javax.swing.JPanel jPanel_Information;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_Mystery;
    private javax.swing.JPanel jPanel_NonFiction;
    private javax.swing.JPanel jPanel_Poetry;
    private javax.swing.JPanel jPanel_Romance;
    private javax.swing.JPanel jPanel_Sub;
    private javax.swing.JScrollPane jScrollPane_Main;
    private javax.swing.JScrollPane jScrollPane_TA;
    private javax.swing.JTextArea jTextArea_Introduction;
    private javax.swing.JLabel mysImage;
    private javax.swing.JLabel mysLabel;
    private javax.swing.JLabel nfImage;
    private javax.swing.JLabel nfLabel;
    private javax.swing.JLabel poetryImage;
    private javax.swing.JLabel poetryLabel;
    private javax.swing.JLabel romImage;
    private javax.swing.JLabel romLabel;
    // End of variables declaration//GEN-END:variables
}
