/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booktap;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MainOptionsScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainOptionsScreen
     */
    public MainOptionsScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Outerpane = new javax.swing.JLayeredPane();
        Outerpanel = new javax.swing.JPanel();
        jLayeredPane_InnerPane = new javax.swing.JLayeredPane();
        jPanel_InnerPanel = new javax.swing.JPanel();
        jLabel_BookTap = new javax.swing.JLabel();
        jLabel_Login = new javax.swing.JButton();
        jButton_Register = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jLabel_Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPTIONS");
        setSize(new java.awt.Dimension(1000, 600));

        Outerpane.setPreferredSize(new java.awt.Dimension(1000, 600));

        Outerpanel.setBackground(new java.awt.Color(43, 37, 56));
        Outerpanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        javax.swing.GroupLayout jLayeredPane_InnerPaneLayout = new javax.swing.GroupLayout(jLayeredPane_InnerPane);
        jLayeredPane_InnerPane.setLayout(jLayeredPane_InnerPaneLayout);
        jLayeredPane_InnerPaneLayout.setHorizontalGroup(
            jLayeredPane_InnerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
        );
        jLayeredPane_InnerPaneLayout.setVerticalGroup(
            jLayeredPane_InnerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        jPanel_InnerPanel.setBackground(new java.awt.Color(17, 94, 111));

        jLabel_BookTap.setBackground(new java.awt.Color(255, 102, 153));
        jLabel_BookTap.setFont(new java.awt.Font("Malgun Gothic", 0, 90)); // NOI18N
        jLabel_BookTap.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_BookTap.setText("BookTap");

        jLabel_Login.setBackground(new java.awt.Color(255, 182, 28));
        jLabel_Login.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(43, 37, 56));
        jLabel_Login.setText("LOGIN");
        jLabel_Login.setBorder(null);
        jLabel_Login.setFocusPainted(false);
        jLabel_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_LoginActionPerformed(evt);
            }
        });

        jButton_Register.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Register.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Register.setText("REGISTER");
        jButton_Register.setBorder(null);
        jButton_Register.setFocusPainted(false);
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        jButton_Exit.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Exit.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Exit.setText("Exit");
        jButton_Exit.setBorder(null);
        jButton_Exit.setFocusPainted(false);
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Interests images/LOGO.PNG"))); // NOI18N
        jLabel_Logo.setPreferredSize(new java.awt.Dimension(87, 87));

        javax.swing.GroupLayout jPanel_InnerPanelLayout = new javax.swing.GroupLayout(jPanel_InnerPanel);
        jPanel_InnerPanel.setLayout(jPanel_InnerPanelLayout);
        jPanel_InnerPanelLayout.setHorizontalGroup(
            jPanel_InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InnerPanelLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addGroup(jPanel_InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InnerPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(337, 337, 337))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InnerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel_BookTap)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InnerPanelLayout.createSequentialGroup()
                        .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jPanel_InnerPanelLayout.setVerticalGroup(
            jPanel_InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InnerPanelLayout.createSequentialGroup()
                .addGroup(jPanel_InnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InnerPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel_BookTap))
                    .addGroup(jPanel_InnerPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout OuterpanelLayout = new javax.swing.GroupLayout(Outerpanel);
        Outerpanel.setLayout(OuterpanelLayout);
        OuterpanelLayout.setHorizontalGroup(
            OuterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuterpanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel_InnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane_InnerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OuterpanelLayout.setVerticalGroup(
            OuterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuterpanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLayeredPane_InnerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OuterpanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel_InnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Outerpane.setLayer(Outerpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout OuterpaneLayout = new javax.swing.GroupLayout(Outerpane);
        Outerpane.setLayout(OuterpaneLayout);
        OuterpaneLayout.setHorizontalGroup(
            OuterpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OuterpaneLayout.createSequentialGroup()
                .addComponent(Outerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OuterpaneLayout.setVerticalGroup(
            OuterpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OuterpaneLayout.createSequentialGroup()
                .addComponent(Outerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Outerpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Outerpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        // TODO add your handling code here:
        Register r=new Register();
        r.show();
        dispose();
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jLabel_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_LoginActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_jLabel_LoginActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon("src/cutiee.png"); 
        int a = JOptionPane.showConfirmDialog(this,"Are you sure you want to logout?","This will redirect to main screen.",JOptionPane.YES_NO_OPTION , JOptionPane.PLAIN_MESSAGE, icon);
        if(a == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainOptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainOptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainOptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainOptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainOptionsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Outerpane;
    private javax.swing.JPanel Outerpanel;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel_BookTap;
    private javax.swing.JButton jLabel_Login;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLayeredPane jLayeredPane_InnerPane;
    private javax.swing.JPanel jPanel_InnerPanel;
    // End of variables declaration//GEN-END:variables
}
