/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booktap;

/**
 *
 * @author DELL
 */

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import javax.swing.border.*;

public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    String username;
    public Profile(String u) {
        this.username = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane = new javax.swing.JScrollPane();
        outerlayeredpane = new javax.swing.JLayeredPane();
        outerpanel = new javax.swing.JPanel();
        innerlayeredpane = new javax.swing.JLayeredPane();
        ineerpanel = new javax.swing.JPanel();
        Homebutton = new javax.swing.JButton();
        Booksbutton = new javax.swing.JButton();
        Postsbutton = new javax.swing.JButton();
        Trendingbutton = new javax.swing.JButton();
        Profileslabel = new javax.swing.JLabel();
        captionlabel = new javax.swing.JLabel();
        Gobackbutton = new javax.swing.JButton();
        usernamelabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        usernametextfield = new javax.swing.JTextField();
        Emailtextfield = new javax.swing.JTextField();
        firstnamelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        lastnametextfield = new javax.swing.JTextField();
        yourdetailspanel = new javax.swing.JPanel();
        yourdetailslabel = new javax.swing.JLabel();
        firstnametextfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        yourdetailspanel1 = new javax.swing.JPanel();
        yourdetailslabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROFILE");
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 600));

        outerpanel.setBackground(new java.awt.Color(43, 37, 56));

        javax.swing.GroupLayout innerlayeredpaneLayout = new javax.swing.GroupLayout(innerlayeredpane);
        innerlayeredpane.setLayout(innerlayeredpaneLayout);
        innerlayeredpaneLayout.setHorizontalGroup(
            innerlayeredpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
        );
        innerlayeredpaneLayout.setVerticalGroup(
            innerlayeredpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        ineerpanel.setBackground(new java.awt.Color(17, 94, 111));
        ineerpanel.setPreferredSize(new java.awt.Dimension(800, 496));

        Homebutton.setBackground(new java.awt.Color(255, 182, 28));
        Homebutton.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        Homebutton.setForeground(new java.awt.Color(43, 37, 56));
        Homebutton.setText("Home");
        Homebutton.setBorder(null);
        Homebutton.setBorderPainted(false);
        Homebutton.setFocusPainted(false);
        Homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomebuttonActionPerformed(evt);
            }
        });

        Booksbutton.setBackground(new java.awt.Color(255, 182, 28));
        Booksbutton.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        Booksbutton.setForeground(new java.awt.Color(43, 37, 56));
        Booksbutton.setText("Books");
        Booksbutton.setBorder(null);
        Booksbutton.setBorderPainted(false);
        Booksbutton.setFocusPainted(false);
        Booksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksbuttonActionPerformed(evt);
            }
        });

        Postsbutton.setBackground(new java.awt.Color(255, 182, 28));
        Postsbutton.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        Postsbutton.setForeground(new java.awt.Color(43, 37, 56));
        Postsbutton.setText("Posts");
        Postsbutton.setBorder(null);
        Postsbutton.setBorderPainted(false);
        Postsbutton.setFocusPainted(false);
        Postsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostsbuttonActionPerformed(evt);
            }
        });

        Trendingbutton.setBackground(new java.awt.Color(255, 182, 28));
        Trendingbutton.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        Trendingbutton.setForeground(new java.awt.Color(43, 37, 56));
        Trendingbutton.setText("Trending");
        Trendingbutton.setBorder(null);
        Trendingbutton.setBorderPainted(false);
        Trendingbutton.setFocusPainted(false);
        Trendingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrendingbuttonActionPerformed(evt);
            }
        });

        Profileslabel.setFont(new java.awt.Font("Malgun Gothic", 0, 58)); // NOI18N
        Profileslabel.setForeground(new java.awt.Color(255, 255, 255));
        Profileslabel.setText("Profile");

        captionlabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        captionlabel.setForeground(new java.awt.Color(255, 255, 255));
        captionlabel.setText("Here you can view your details, liked genres and posts");

        Gobackbutton.setBackground(new java.awt.Color(255, 182, 28));
        Gobackbutton.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        Gobackbutton.setForeground(new java.awt.Color(43, 37, 56));
        Gobackbutton.setText("Go Back");
        Gobackbutton.setBorder(null);
        Gobackbutton.setBorderPainted(false);
        Gobackbutton.setFocusPainted(false);
        Gobackbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobackbuttonActionPerformed(evt);
            }
        });

        usernamelabel.setBackground(new java.awt.Color(255, 255, 255));
        usernamelabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        usernamelabel.setText("Username");

        Emaillabel.setBackground(new java.awt.Color(255, 255, 255));
        Emaillabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        Emaillabel.setForeground(new java.awt.Color(255, 255, 255));
        Emaillabel.setText("E-Mail");

        usernametextfield.setBackground(new java.awt.Color(43, 37, 56));
        usernametextfield.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        usernametextfield.setForeground(new java.awt.Color(255, 255, 255));
        usernametextfield.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        Emailtextfield.setBackground(new java.awt.Color(43, 37, 56));
        Emailtextfield.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Emailtextfield.setForeground(new java.awt.Color(255, 255, 255));
        Emailtextfield.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        firstnamelabel.setBackground(new java.awt.Color(255, 255, 255));
        firstnamelabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        firstnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnamelabel.setText("First Name");

        lastnamelabel.setBackground(new java.awt.Color(255, 255, 255));
        lastnamelabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        lastnamelabel.setForeground(new java.awt.Color(255, 255, 255));
        lastnamelabel.setText("Last Name");

        lastnametextfield.setBackground(new java.awt.Color(43, 37, 56));
        lastnametextfield.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lastnametextfield.setForeground(new java.awt.Color(255, 255, 255));
        lastnametextfield.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lastnametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametextfieldActionPerformed(evt);
            }
        });

        yourdetailspanel.setBackground(new java.awt.Color(43, 37, 56));

        yourdetailslabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        yourdetailslabel.setForeground(new java.awt.Color(255, 255, 255));
        yourdetailslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourdetailslabel.setText("Your Details");

        javax.swing.GroupLayout yourdetailspanelLayout = new javax.swing.GroupLayout(yourdetailspanel);
        yourdetailspanel.setLayout(yourdetailspanelLayout);
        yourdetailspanelLayout.setHorizontalGroup(
            yourdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourdetailspanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(yourdetailslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        yourdetailspanelLayout.setVerticalGroup(
            yourdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourdetailspanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(yourdetailslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        firstnametextfield.setBackground(new java.awt.Color(43, 37, 56));
        firstnametextfield.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        firstnametextfield.setForeground(new java.awt.Color(255, 255, 255));
        firstnametextfield.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        firstnametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametextfieldActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 182, 28));
        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(43, 37, 56));
        jButton1.setText("Settings");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ineerpanelLayout = new javax.swing.GroupLayout(ineerpanel);
        ineerpanel.setLayout(ineerpanelLayout);
        ineerpanelLayout.setHorizontalGroup(
            ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ineerpanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ineerpanelLayout.createSequentialGroup()
                        .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yourdetailspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Profileslabel)
                            .addComponent(captionlabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ineerpanelLayout.createSequentialGroup()
                        .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ineerpanelLayout.createSequentialGroup()
                                .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Booksbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Postsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Trendingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ineerpanelLayout.createSequentialGroup()
                                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernamelabel)
                                    .addComponent(firstnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnamelabel))
                                .addGap(158, 158, 158)
                                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastnamelabel)
                                    .addComponent(Emaillabel))))
                        .addGap(18, 18, 18)
                        .addComponent(Gobackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        ineerpanelLayout.setVerticalGroup(
            ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ineerpanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Booksbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trendingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gobackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Profileslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(captionlabel)
                .addGap(28, 28, 28)
                .addComponent(yourdetailspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emaillabel)
                    .addComponent(usernamelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnamelabel)
                    .addComponent(lastnamelabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ineerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        jPanel2.setBackground(new java.awt.Color(17, 94, 111));

        yourdetailspanel1.setBackground(new java.awt.Color(43, 37, 56));

        yourdetailslabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        yourdetailslabel1.setForeground(new java.awt.Color(255, 255, 255));
        yourdetailslabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourdetailslabel1.setText("Liked Genres");

        javax.swing.GroupLayout yourdetailspanel1Layout = new javax.swing.GroupLayout(yourdetailspanel1);
        yourdetailspanel1.setLayout(yourdetailspanel1Layout);
        yourdetailspanel1Layout.setHorizontalGroup(
            yourdetailspanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourdetailspanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(yourdetailslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        yourdetailspanel1Layout.setVerticalGroup(
            yourdetailspanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourdetailspanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(yourdetailslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextArea1.setBackground(new java.awt.Color(43, 37, 56));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Malgun Gothic", 1, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yourdetailspanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(yourdetailspanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(17, 94, 111));

        jPanel3.setBackground(new java.awt.Color(43, 37, 56));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Posts");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        displayMyPosts();
        java.awt.GridLayout jPanel4Layout = new java.awt.GridLayout(0, 1);
        jPanel4.setLayout(jPanel4Layout);
        jScrollPane2.setViewportView(jPanel4);
        jScrollPane2.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2))
        );

        javax.swing.GroupLayout outerpanelLayout = new javax.swing.GroupLayout(outerpanel);
        outerpanel.setLayout(outerpanelLayout);
        outerpanelLayout.setHorizontalGroup(
            outerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outerpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(outerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ineerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(innerlayeredpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        outerpanelLayout.setVerticalGroup(
            outerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outerpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(outerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(innerlayeredpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(outerpanelLayout.createSequentialGroup()
                        .addComponent(ineerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        outerlayeredpane.setLayer(outerpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout outerlayeredpaneLayout = new javax.swing.GroupLayout(outerlayeredpane);
        outerlayeredpane.setLayout(outerlayeredpaneLayout);
        outerlayeredpaneLayout.setHorizontalGroup(
            outerlayeredpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        outerlayeredpaneLayout.setVerticalGroup(
            outerlayeredpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scrollpane.setViewportView(outerlayeredpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );

        displayLikedGenres();
        displayUserDetails();
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomebuttonActionPerformed
        // TODO add your handling code here:
        HomePage h = new HomePage(this.username);
        h.show();
        dispose();
    }//GEN-LAST:event_HomebuttonActionPerformed

    private void BooksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksbuttonActionPerformed
        // TODO add your handling code here:
        BooksPage b = new BooksPage(this.username);
        b.show();
        dispose();
    }//GEN-LAST:event_BooksbuttonActionPerformed

    private void PostsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostsbuttonActionPerformed
        // TODO add your handling code here:
        Posts p = new Posts(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_PostsbuttonActionPerformed

    private void TrendingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrendingbuttonActionPerformed
        // TODO add your handling code here:
        Trending t = new Trending(this.username);
        t.show();
        dispose();
    }//GEN-LAST:event_TrendingbuttonActionPerformed

    private void GobackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobackbuttonActionPerformed
        // TODO add your handling code here:
        HomePage h = new HomePage(this.username);
        h.show();
        dispose();
    }//GEN-LAST:event_GobackbuttonActionPerformed

    private void lastnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametextfieldActionPerformed

    private void firstnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametextfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Settings s = new Settings(this.username);
        s.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void displayUserDetails() {
    	try {    
			Class.forName("oracle.jdbc.driver.OracleDriver"); 
 
			Connection con=DriverManager.getConnection(  
		    "jdbc:oracle:thin:@localhost:1521:xe","it175","sravya");  
 
			Statement stmt=con.createStatement(); 	
            ResultSet rs = stmt.executeQuery("SELECT * FROM USERS WHERE USERNAME = '" + this.username + "'");
            
		    while(rs.next())  {
		    	String userName = rs.getString(1);
		    	String firstname = rs.getString(2);
		    	String lastname = rs.getString(3);
		    	String email = rs.getString(4);
		    	usernametextfield.setText(userName);
		    	firstnametextfield.setText(firstname);
		    	lastnametextfield.setText(lastname);
		    	Emailtextfield.setText(email);
		    	
		    }
 
            con.close();  
        } catch(Exception e) {
            System.out.println(e);
        }    

    }
    
    public void displayLikedGenres() {
        jTextArea1.setBorder(new EmptyBorder(1, 5, 1, 1));
        jScrollPane1.setBorder(null);
    	try {    
			Class.forName("oracle.jdbc.driver.OracleDriver"); 
 
			Connection con=DriverManager.getConnection(  
		    "jdbc:oracle:thin:@localhost:1521:xe","it175","sravya");  
 
			Statement stmt=con.createStatement(); 	
            ResultSet rs = stmt.executeQuery("SELECT * FROM LIKEDGENRES WHERE USERNAME = '" + username + "'");
            
            String allLikedGenres = "";
            int flag = 0;
		    while(rs.next())  {
		    	String g = rs.getString(2);
		    	allLikedGenres += g + "\n";
		    	flag = 1;
		    }
		    
		    if (flag == 1) {
		    	jTextArea1.setText(allLikedGenres);
		    } else {
		    	jTextArea1.setText("YOU HAVE NO LIKED GENRES!");
		    }
		    
            con.close();  
        } catch(Exception e) {
            System.out.println(e);
        }    
    }
    
    public void displayMyPosts() {    	
    	jPanel4.removeAll();
    	validate();
        repaint();
        jScrollPane2.validate();
        int flag = 0;
        String bookname = "";
        String authorName = "";
        String genre = "";
        String post = "";
        Float rating = 0F;
        
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver"); 
            Connection con=DriverManager.getConnection(  "jdbc:oracle:thin:@localhost:1521:xe","it175","sravya");  
            Statement stmt=con.createStatement(); 	
            ResultSet rs = stmt.executeQuery("SELECT * FROM POSTS WHERE USERNAME = '" + username + "' ORDER BY TIME DESC");
            
            while(rs.next())  {
                JLabel BookLabel = new JLabel();
                bookname = rs.getString(1);
                authorName = rs.getString(2);
                genre = rs.getString(3);
                post = rs.getString(4);
                rating = rs.getFloat(5);
                flag = 1;

                Blob b = rs.getBlob(6);
                byte barr[] = b.getBytes(1,(int)b.length());
                ImageIcon icon = new ImageIcon(barr);
                java.awt.Image img = icon.getImage();
                java.awt.Image scale = img.getScaledInstance(200, 300,java.awt.Image.SCALE_SMOOTH);
                ImageIcon scaled = new ImageIcon(scale);
                BookLabel.setIcon(scaled);   
		    	
                JPanel mainPanel = new javax.swing.JPanel();
                mainPanel.setBackground(new java.awt.Color(17, 94, 111));
                JPanel PostsPanel = new javax.swing.JPanel();
                JScrollPane SummaryScrollPane = new javax.swing.JScrollPane();
                JTextArea SummaryTextArea = new javax.swing.JTextArea();
                JLabel bookNameLabel = new javax.swing.JLabel();
                JLabel authorNameLabel = new javax.swing.JLabel();
                JLabel genreLabel = new javax.swing.JLabel();
                JLabel RatingLabel = new javax.swing.JLabel();
                JLabel ReviewLabel = new javax.swing.JLabel();
                JTextField BookTextField = new javax.swing.JTextField();
                JTextField AuthorTextField = new javax.swing.JTextField();
                JTextField GenreTextField = new javax.swing.JTextField();
                JTextField jTextField1 = new javax.swing.JTextField();
                JLabel Usernamelabel = new javax.swing.JLabel();
                JTextField usernametextfield = new javax.swing.JTextField();
                setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(886, 345));

                PostsPanel.setBackground(new java.awt.Color(43, 37, 56));
                PostsPanel.setPreferredSize(new java.awt.Dimension(886, 400));

                SummaryTextArea.setBackground(new java.awt.Color(17, 94, 111));
                SummaryTextArea.setColumns(20);
                SummaryTextArea.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
                SummaryTextArea.setText(post);
                SummaryTextArea.setBorder(new EmptyBorder(5, 5, 5, 5));
                SummaryTextArea.setForeground(new java.awt.Color(255, 255, 255));
                SummaryTextArea.setLineWrap(true);
                SummaryTextArea.setRows(5);
                SummaryTextArea.setWrapStyleWord(true);
                SummaryScrollPane.setViewportView(SummaryTextArea);
                SummaryScrollPane.setBorder(null);

                bookNameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
                bookNameLabel.setForeground(new java.awt.Color(255, 255, 255));
                bookNameLabel.setText("Book");

                authorNameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
                authorNameLabel.setForeground(new java.awt.Color(255, 255, 255));
                authorNameLabel.setText("Author ");

                genreLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
                genreLabel.setForeground(new java.awt.Color(255, 255, 255));
                genreLabel.setText("Genre");

                RatingLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
                RatingLabel.setForeground(new java.awt.Color(255, 255, 255));
                RatingLabel.setText("Rating");

                ReviewLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
                ReviewLabel.setForeground(new java.awt.Color(255, 255, 255));
                ReviewLabel.setText("Review");

                BookTextField.setBackground(new java.awt.Color(17, 94, 111));
                BookTextField.setText(bookname);
                BookTextField.setBorder(new EmptyBorder(0, 5, 0, 0));
                BookTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
                BookTextField.setForeground(new java.awt.Color(255, 255, 255));

                AuthorTextField.setBackground(new java.awt.Color(17, 94, 111));
                AuthorTextField.setText(authorName);
                AuthorTextField.setBorder(new EmptyBorder(0, 5, 0, 0));
                AuthorTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
                AuthorTextField.setForeground(new java.awt.Color(255, 255, 255));

                GenreTextField.setBackground(new java.awt.Color(17, 94, 111));
                GenreTextField.setBorder(new EmptyBorder(0, 5, 0, 0));
                GenreTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
                GenreTextField.setForeground(new java.awt.Color(255, 255, 255));
                GenreTextField.setText(genre);
                GenreTextField.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    }
                });

                jTextField1.setBackground(new java.awt.Color(17, 94, 111));
                jTextField1.setBorder(new EmptyBorder(0, 5, 0, 0));
                jTextField1.setFont(new java.awt.Font("Malgun Gothic", 1, 40)); // NOI18N
                jTextField1.setForeground(new java.awt.Color(255, 255, 255));
                jTextField1.setText(rating.toString());
                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    }
                });

                Usernamelabel.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
                Usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
                Usernamelabel.setText("Username");

                usernametextfield.setBackground(new java.awt.Color(17, 94, 111));
                usernametextfield.setBorder(new EmptyBorder(0, 5, 0, 0));
                usernametextfield.setText(username);
                usernametextfield.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
                usernametextfield.setForeground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout PostsPanelLayout = new javax.swing.GroupLayout(PostsPanel);
                PostsPanel.setLayout(PostsPanelLayout);
                PostsPanelLayout.setHorizontalGroup(
                    PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PostsPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(BookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReviewLabel)
                            .addGroup(PostsPanelLayout.createSequentialGroup()
                                .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(authorNameLabel)
                                    .addComponent(genreLabel)
                                    .addComponent(Usernamelabel))
                                .addGap(30, 30, 30)
                                .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PostsPanelLayout.createSequentialGroup()
                                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(usernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PostsPanelLayout.createSequentialGroup()
                                        .addComponent(BookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RatingLabel)
                                        .addGap(11, 11, 11))))
                            .addComponent(SummaryScrollPane))
                        .addContainerGap(44, Short.MAX_VALUE))
                );
                PostsPanelLayout.setVerticalGroup(
                    PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PostsPanelLayout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PostsPanelLayout.createSequentialGroup()
                                .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PostsPanelLayout.createSequentialGroup()
                                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Usernamelabel)
                                            .addComponent(usernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(bookNameLabel)
                                            .addComponent(BookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(authorNameLabel)
                                            .addComponent(AuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PostsPanelLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(RatingLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ReviewLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SummaryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BookLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                );		        
            mainPanel.add(PostsPanel);
            JLabel gap = new JLabel();
            gap.setBackground(Color.WHITE);
            mainPanel.add(gap);
            jPanel4.add(mainPanel);

            } 

            if (flag == 0) {
                JLabel message = new JLabel("You haven't posted anything yet!");
                message.setFont(new Font("Malgun Gothic", Font.BOLD, 30));
                message.setForeground(Color.WHITE);
                jPanel4.setBackground(new java.awt.Color(17, 94, 111));
                jPanel4.setBorder(new EmptyBorder(5, 200, 20, 5));
                jScrollPane2.setBorder(new LineBorder(Color.BLACK));
                jPanel4.add(message);
            }
		    
        } catch (Exception e) {
        	System.out.println(e);
        }
    	
    	pack();
        setPreferredSize(new Dimension(1000, 600));
        setVisible(true);
    }


    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Profile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booksbutton;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JTextField Emailtextfield;
    private javax.swing.JButton Gobackbutton;
    private javax.swing.JButton Homebutton;
    private javax.swing.JButton Postsbutton;
    private javax.swing.JLabel Profileslabel;
    private javax.swing.JButton Trendingbutton;
    private javax.swing.JLabel captionlabel;
    private javax.swing.JLabel firstnamelabel;
    private javax.swing.JTextField firstnametextfield;
    private javax.swing.JPanel ineerpanel;
    private javax.swing.JLayeredPane innerlayeredpane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JTextField lastnametextfield;
    private javax.swing.JLayeredPane outerlayeredpane;
    private javax.swing.JPanel outerpanel;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JTextField usernametextfield;
    private javax.swing.JLabel yourdetailslabel;
    private javax.swing.JLabel yourdetailslabel1;
    private javax.swing.JPanel yourdetailspanel;
    private javax.swing.JPanel yourdetailspanel1;
    // End of variables declaration//GEN-END:variables
}
