/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booktap;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    String username;
    public Register() {
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterPanel = new javax.swing.JPanel();
        Registerlabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        jButton_GoBack = new javax.swing.JButton();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        ReenterPassLabel = new javax.swing.JLabel();
        ReenterPassTextField = new javax.swing.JPasswordField();
        jButton_Confirm = new javax.swing.JButton();
        BackgoundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER");
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegisterPanel.setBackground(new java.awt.Color(0,0,0,200));

        Registerlabel.setBackground(new java.awt.Color(255, 200, 90));
        Registerlabel.setFont(new java.awt.Font("Malgun Gothic", 1, 45)); // NOI18N
        Registerlabel.setForeground(new java.awt.Color(255, 200, 90));
        Registerlabel.setText("REGISTER");

        UsernameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 200, 90));
        UsernameLabel.setText("Username  ");

        PasswordLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 200, 90));
        PasswordLabel.setText("Password ");

        UsernameTextField.setBackground(new java.awt.Color(255, 200, 90));
        UsernameTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        UsernameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setBackground(new java.awt.Color(255, 200, 90));
        PasswordTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        PasswordTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        jButton_GoBack.setBackground(new java.awt.Color(255, 182, 28));
        jButton_GoBack.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_GoBack.setText("Go Back");
        jButton_GoBack.setBorder(null);
        jButton_GoBack.setFocusPainted(false);
        jButton_GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GoBackActionPerformed(evt);
            }
        });

        firstnameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(255, 200, 90));
        firstnameLabel.setText("First Name  ");

        lastnameLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lastnameLabel.setForeground(new java.awt.Color(255, 200, 90));
        lastnameLabel.setText("Last Name  ");

        emaillabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        emaillabel.setForeground(new java.awt.Color(255, 200, 90));
        emaillabel.setText("Email Address  ");

        LastNameTextField.setBackground(new java.awt.Color(255, 200, 90));
        LastNameTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        LastNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        FirstNameTextField.setBackground(new java.awt.Color(255, 200, 90));
        FirstNameTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        FirstNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        EmailTextField.setBackground(new java.awt.Color(255, 200, 90));
        EmailTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        EmailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        ReenterPassLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        ReenterPassLabel.setForeground(new java.awt.Color(255, 200, 90));
        ReenterPassLabel.setText("Re-Enter Password ");

        ReenterPassTextField.setBackground(new java.awt.Color(255, 200, 90));
        ReenterPassTextField.setFont(new java.awt.Font("Malgun Gothic", 1, 13)); // NOI18N
        ReenterPassTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        ReenterPassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReenterPassTextFieldActionPerformed(evt);
            }
        });

        jButton_Confirm.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Confirm.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Confirm.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Confirm.setText("Confirm");
        jButton_Confirm.setBorder(null);
        jButton_Confirm.setFocusPainted(false);
        jButton_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Registerlabel)
                .addGap(232, 232, 232))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsernameLabel)
                    .addComponent(lastnameLabel)
                    .addComponent(PasswordLabel)
                    .addComponent(ReenterPassLabel)
                    .addComponent(emaillabel)
                    .addComponent(firstnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReenterPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(jButton_GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Registerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameLabel))
                .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_GoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(RegisterPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordLabel)
                            .addGroup(RegisterPanelLayout.createSequentialGroup()
                                .addComponent(PasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(20, 20, 20)
                        .addGroup(RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReenterPassLabel)
                            .addGroup(RegisterPanelLayout.createSequentialGroup()
                                .addComponent(ReenterPassTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addGap(31, 31, 31)
                        .addComponent(jButton_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))))
        );

        getContentPane().add(RegisterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 690, 500));

        BackgoundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Interests images/LoginCoverImage.jpg"))); // NOI18N
        getContentPane().add(BackgoundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1014, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void jButton_GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GoBackActionPerformed
        // TODO add your handling code here:
        MainOptionsScreen var=new MainOptionsScreen();
        var.show();
        dispose();
    }//GEN-LAST:event_jButton_GoBackActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void ReenterPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReenterPassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReenterPassTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void jButton_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        String username = UsernameTextField.getText();
        String firstname = FirstNameTextField.getText();
        String lastname = LastNameTextField.getText();
        String email = EmailTextField.getText();
        String password = PasswordTextField.getText();
        String repass = ReenterPassTextField.getText();       
        if(username.isEmpty() || firstname.isEmpty() || lastname.isEmpty() || email.isEmpty() || password.isEmpty() || repass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Incomplete details. Please enter details again."); 
            UsernameTextField.setText("");
            FirstNameTextField.setText("");
            LastNameTextField.setText("");
            EmailTextField.setText("");
            PasswordTextField.setText("");
            ReenterPassTextField.setText("");
        }
        else{
            if(password.equals(repass)){
                try{
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","it175","sravya");
                    PreparedStatement pstmt = con.prepareStatement("INSERT INTO USERS VALUES(?,?,?,?,?)");
                    Statement stmt1 = con.createStatement();
                    ResultSet rs=stmt1.executeQuery("SELECT USERNAME FROM USERS WHERE USERNAME = '" + username + "'");
                    while(rs.next())
                    {
                        flag = 1;      
                    }
                    
                    if(flag == 1){
                        JOptionPane.showMessageDialog(this,"Username already exists. Please enter details again.");
                        UsernameTextField.setText("");
                        FirstNameTextField.setText("");
                        LastNameTextField.setText("");
                        EmailTextField.setText("");
                        PasswordTextField.setText("");
                        ReenterPassTextField.setText(""); 
                    }
                    
                    else{
                        pstmt.setString(1, username);  
                        pstmt.setString(2, firstname);  
                        pstmt.setString(3, lastname);  
                        pstmt.setString(4, email);  
                        pstmt.setString(5, password);   
                        ResultSet rs1 = pstmt.executeQuery();  
                        JOptionPane.showMessageDialog(this, "Successfully registered!");  
                        Interests i = new Interests(username);
                        i.show();
                        dispose();                        
                    }    
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Passwords do not match. Please enter details again.");
                UsernameTextField.setText("");
                FirstNameTextField.setText("");
                LastNameTextField.setText("");
                EmailTextField.setText("");
                PasswordTextField.setText("");
                ReenterPassTextField.setText(""); 
            }  
        } 
    }//GEN-LAST:event_jButton_ConfirmActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgoundImageLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel ReenterPassLabel;
    private javax.swing.JPasswordField ReenterPassTextField;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JLabel Registerlabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JButton jButton_Confirm;
    private javax.swing.JButton jButton_GoBack;
    private javax.swing.JLabel lastnameLabel;
    // End of variables declaration//GEN-END:variables
}
