/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package booktap;

/**
 *
 * @author sravy
 */
public class Trending extends javax.swing.JFrame {

    /**
     * Creates new form Trending
     */
    String username;
    public Trending(String u) {
        this.username = u;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jButton_Home = new javax.swing.JButton();
        jButton_Books = new javax.swing.JButton();
        jButton_Posts = new javax.swing.JButton();
        jButton_Trending = new javax.swing.JButton();
        jButton_Settings = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Fiction = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_Adventure = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_Romance = new javax.swing.JButton();
        jButton_Poetry = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Classics = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton_NonFiction = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton_Horror = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_Mystery = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton_Fantasy = new javax.swing.JButton();
        jButton_Profile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRENDING");
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(43, 37, 56));

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1191, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(17, 94, 111));

        jButton_Home.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Home.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Home.setText("Home");
        jButton_Home.setBorder(null);
        jButton_Home.setFocusPainted(false);
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        jButton_Books.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Books.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Books.setText("Books");
        jButton_Books.setBorder(null);
        jButton_Books.setFocusPainted(false);
        jButton_Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BooksActionPerformed(evt);
            }
        });

        jButton_Posts.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Posts.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Posts.setText("Posts");
        jButton_Posts.setBorder(null);
        jButton_Posts.setFocusPainted(false);
        jButton_Posts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PostsActionPerformed(evt);
            }
        });

        jButton_Trending.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Trending.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Trending.setText("Trending");
        jButton_Trending.setBorder(null);
        jButton_Trending.setFocusPainted(false);
        jButton_Trending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TrendingActionPerformed(evt);
            }
        });

        jButton_Settings.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Settings.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Settings.setText("Settings");
        jButton_Settings.setBorder(null);
        jButton_Settings.setFocusPainted(false);
        jButton_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SettingsActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/fiction.jpeg"))); // NOI18N

        jButton_Fiction.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Fiction.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Fiction.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Fiction.setText("TOP 3 FICTION");
        jButton_Fiction.setBorder(null);
        jButton_Fiction.setFocusPainted(false);
        jButton_Fiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FictionActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/adv.jpeg"))); // NOI18N

        jButton_Adventure.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Adventure.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Adventure.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Adventure.setText("TOP 3 ADVENTURE");
        jButton_Adventure.setBorder(null);
        jButton_Adventure.setFocusPainted(false);
        jButton_Adventure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdventureActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/romance.jpeg"))); // NOI18N

        jButton_Romance.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Romance.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Romance.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Romance.setText("TOP 3 ROMANCE");
        jButton_Romance.setBorder(null);
        jButton_Romance.setFocusPainted(false);
        jButton_Romance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RomanceActionPerformed(evt);
            }
        });

        jButton_Poetry.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Poetry.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Poetry.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Poetry.setText("TOP 3 POETRY");
        jButton_Poetry.setBorder(null);
        jButton_Poetry.setFocusPainted(false);
        jButton_Poetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PoetryActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/drama.jpeg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/class.jpeg"))); // NOI18N

        jButton_Classics.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Classics.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Classics.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Classics.setText("TOP 3 CLASSICS");
        jButton_Classics.setBorder(null);
        jButton_Classics.setFocusPainted(false);
        jButton_Classics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClassicsActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/non-fiction.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jButton_NonFiction.setBackground(new java.awt.Color(251, 120, 74));
        jButton_NonFiction.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_NonFiction.setForeground(new java.awt.Color(43, 37, 56));
        jButton_NonFiction.setText("TOP 3 NON-FICTION");
        jButton_NonFiction.setBorder(null);
        jButton_NonFiction.setFocusPainted(false);
        jButton_NonFiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NonFictionActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/horror.jpeg"))); // NOI18N

        jButton_Horror.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Horror.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Horror.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Horror.setText("TOP 3 HORROR");
        jButton_Horror.setBorder(null);
        jButton_Horror.setFocusPainted(false);
        jButton_Horror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HorrorActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/thriller.jpeg"))); // NOI18N

        jButton_Mystery.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Mystery.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Mystery.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Mystery.setText("TOP 3 MYSTERY");
        jButton_Mystery.setBorder(null);
        jButton_Mystery.setFocusPainted(false);
        jButton_Mystery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MysteryActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genres/fantasy.jpeg"))); // NOI18N

        jButton_Fantasy.setBackground(new java.awt.Color(251, 120, 74));
        jButton_Fantasy.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton_Fantasy.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Fantasy.setText("TOP 3 FANTASY");
        jButton_Fantasy.setBorder(null);
        jButton_Fantasy.setFocusPainted(false);
        jButton_Fantasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FantasyActionPerformed(evt);
            }
        });

        jButton_Profile.setBackground(new java.awt.Color(255, 182, 28));
        jButton_Profile.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jButton_Profile.setForeground(new java.awt.Color(43, 37, 56));
        jButton_Profile.setText("Profile");
        jButton_Profile.setBorder(null);
        jButton_Profile.setFocusPainted(false);
        jButton_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton_Fiction, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Adventure, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(jButton_Romance, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Trending, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton_Poetry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_NonFiction, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(jButton_Fantasy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton_Classics, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Mystery, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(jButton_Horror, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Books, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Trending, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Fiction, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton_Adventure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Romance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Fantasy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_Poetry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_NonFiction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Classics, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Horror, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Mystery, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
        HomePage h = new HomePage(this.username);
        h.show();
        dispose();
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void jButton_PostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PostsActionPerformed
        // TODO add your handling code here:
        Posts p = new Posts(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_PostsActionPerformed

    private void jButton_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SettingsActionPerformed
        // TODO add your handling code here:
        Settings s = new Settings(this.username);
        s.show();
        dispose();
    }//GEN-LAST:event_jButton_SettingsActionPerformed

    private void jButton_FictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FictionActionPerformed
        // TODO add your handling code here:
        String a = jButton_Fiction.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
        //TrendList t = new TrendList();
        //t.show();
        //dispose();
    }//GEN-LAST:event_jButton_FictionActionPerformed

    private void jButton_AdventureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdventureActionPerformed
        // TODO add your handling code here:
        String a = jButton_Adventure.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre, username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_AdventureActionPerformed

    private void jButton_RomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RomanceActionPerformed
        // TODO add your handling code here:
        String a = jButton_Romance.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre, username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_RomanceActionPerformed

    private void jButton_PoetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PoetryActionPerformed
        // TODO add your handling code here:
        String a = jButton_Poetry.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_PoetryActionPerformed

    private void jButton_NonFictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NonFictionActionPerformed
        // TODO add your handling code here:
        String a = jButton_NonFiction.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_NonFictionActionPerformed

    private void jButton_FantasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FantasyActionPerformed
        // TODO add your handling code here:
        String a = jButton_Fantasy.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_FantasyActionPerformed

    private void jButton_ClassicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClassicsActionPerformed
        // TODO add your handling code here:
        String a = jButton_Classics.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_ClassicsActionPerformed

    private void jButton_MysteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MysteryActionPerformed
        // TODO add your handling code here:
        String a = jButton_Mystery.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_MysteryActionPerformed

    private void jButton_HorrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HorrorActionPerformed
        // TODO add your handling code here:
        String a = jButton_Horror.getText();
        String genre = a.substring(6, 7) + a.substring(7,a.length()).toLowerCase();
        new TrendList(genre,username).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton_HorrorActionPerformed

    private void jButton_BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BooksActionPerformed
        // TODO add your handling code here:
        BooksPage b = new BooksPage(this.username);
        b.show();
        dispose();
    }//GEN-LAST:event_jButton_BooksActionPerformed

    private void jButton_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfileActionPerformed
        // TODO add your handling code here:
        Profile p = new Profile(this.username);
        p.show();
        dispose();
    }//GEN-LAST:event_jButton_ProfileActionPerformed

    private void jButton_TrendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TrendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TrendingActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Trending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Trending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Trending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Trending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Trending().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Adventure;
    private javax.swing.JButton jButton_Books;
    private javax.swing.JButton jButton_Classics;
    private javax.swing.JButton jButton_Fantasy;
    private javax.swing.JButton jButton_Fiction;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Horror;
    private javax.swing.JButton jButton_Mystery;
    private javax.swing.JButton jButton_NonFiction;
    private javax.swing.JButton jButton_Poetry;
    private javax.swing.JButton jButton_Posts;
    private javax.swing.JButton jButton_Profile;
    private javax.swing.JButton jButton_Romance;
    private javax.swing.JButton jButton_Settings;
    private javax.swing.JButton jButton_Trending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
